### ISSUE TITLE
Does not compile with arduino ide adafruit feather M4 express

### ISSUE THREAD

**Issue by jps2000** [ncmreynolds/ld2410#4]
Hi
lp2410.cpp reports error[-Werror=teturn type]
Control reaches end of non-void function
Cure:
insert return true; in line 448 and line 756
then everything works fine

from www: How do you fix control reaches end of non void function?
If control reaches the end of a function and no return is encountered, GCC assumes a return with no return value. However, for this, the function requires a return value. At the end of the function, add a return statement that returns a suitable return value, even if control never reaches there.

**Comment by ncmreynolds** [comment]
Thanks for spotting this, surprised it didn't fail on an ESP32. Now fixed in 0.1.2+ which I'll do a release of once I've looked at a PR I have for this library.
