### ISSUE TITLE
LD1115H support

### ISSUE THREAD

**Issue by HomeKidd** [ncmreynolds/ld2410#8]
Hi! 
Thanks for your time and effort you've put into this library!
Do you have any plans to make it compatible with the [HLK-LD1115H](https://s.click.aliexpress.com/e/_DCz4yB7) too? I can't find any (standalone) library for this mmWave sensor... 😄

**Comment by ncmreynolds** [comment]
It looks simple enough with human readable UART commands but I'm afraid I don't have one to work with.
